### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by rno0n** [haiibo/OpenWrt#134]
![1696135132974](https://github.com/haiibo/OpenWrt/assets/66623802/558662dd-ef42-4398-9fca-4c0cd43cf185)

**Comment by gtang8** [comment]
![Uploading image.png…]()

**Comment by gtang8** [comment]
![image](https://github.com/haiibo/OpenWrt/assets/74369627/390bdd5c-6c2d-4fb2-aeb4-16815805848d)

**Comment by geekbb** [comment]
一样

**Comment by goodmen001** [comment]
取消 usb-audio 可以编译，但是passwall 还是不能正常使用！
