### ISSUE TITLE
关于USB自动挂载

### ISSUE THREAD

**Issue by lzqd** [haiibo/OpenWrt#17]
关于USB自动挂载无法和F大的固件一样自动挂载，移动硬盘为ntfs格式的。

**Comment by haiibo** [comment]
换一个格式或者手动挂载，ntfs无法自动挂载，F大的也是

**Comment by haiibo** [comment]
也有可能是脏卷问题

**Comment by lzqd** [comment]
> 也有可能是脏卷问题

挂载的移动硬盘格式化了也无法自动挂载，由于要插到电脑上复制电影所以只能用NTFS格式，手动挂载的话定期重启会丢盘，希望有时间能修复一下这个问题

**Comment by haiibo** [comment]
你使用f大的能自动挂载吗，你试试，挂载这个问题是F大的内核包里面的，好像跟编译没有关系，你用的PLUS版本吗

**Comment by haiibo** [comment]
我把u盘格式化ntfs格式使用F大固件试了也是不能自动挂载的，其他格式可以

**Comment by haiibo** [comment]
外界硬盘建议你用plus版本   精简版主打科学上网的

**Comment by lzqd** [comment]
> 
能把存储恢复吗？
我不需要这么多插件，有存储，docker和科学上网就够了
