### ISSUE TITLE
大佬，自己编译的时候，出现这些错误，是哪原因呢

### ISSUE THREAD

**Issue by 5la** [haiibo/OpenWrt#20]
Configuring luci-i18n-nlbwmon-zh-cn.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:111: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

编译是好几次都是这样~

**Comment by haiibo** [comment]
https://github.com/QiuSimons/openwrt-mos/issues/126

**Comment by haiibo** [comment]
https://github.com/QiuSimons/openwrt-mos/issues/126#issue-1288339442
