### ISSUE TITLE
最近两天编译都会出现这个错误~

### ISSUE THREAD

**Issue by 5la** [haiibo/OpenWrt#21]
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:111: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

大佬能看下是啥原因吗

**Comment by haiibo** [comment]
缺少 lua-neturl 依赖
添加：svn co https://github.com/fw876/helloworld/trunk/lua-neturl package/lua-neturl 到 diy-part2.sh即可
