### ISSUE TITLE
R2S最新版 在线用户和网络监控/实时 没了

### ISSUE THREAD

**Issue by aoxueos** [haiibo/OpenWrt#23]
R2S最新版 在线用户和网络监控/实时 没了

**Comment by haiibo** [comment]
这个是之前源码作者更新源码。和宽带监控里面的显示重复了，我就换回之前的源码了，如果你觉得更新后的好用我可以换回来

**Comment by aoxueos** [comment]
谢谢大佬看到了我的留言。我觉得还是两个都有好用，因为现在带宽监控的实时不会显示ipv6信息，而在线用户可以显示v6的地址，用来对adg数据方便些，对于我这种有v6需求的相对不便。另外是否可以扩大一点r2s的根目录容量，我现在就开了个adg只剩62M可用。

**Comment by aoxueos** [comment]
> 这个是之前源码作者更新源码，源码好像有BUG显示一两秒的实际数据，马上就就变成了暂无数据记录，我就换回之前的源码了，如果你觉得更新后的好用我可以换回来

谢谢大佬看到了我的留言。我觉得还是两个都有好用，因为现在带宽监控的实时不会显示ipv6信息，而在线用户可以显示v6的地址，用来对adg数据方便些，对于我这种有v6需求的相对不便。另外是否可以扩大一点r2s的根目录容量，我现在就开了个adg只剩62M可用。

**Comment by haiibo** [comment]
你的adg日志时间设置的多久，日志尽量设置24小时，这个日志很占用内存

**Comment by aoxueos** [comment]
> 你的adg日志时间设置的多久，日志尽量设置24小时，这个日志很占用内存

没有启用，只起用了统计。那个源码明天编译的版本会同步吗。谢谢大佬，辛苦了

**Comment by haiibo** [comment]
明天上午编译的就有了，我今天改的源码

**Comment by aoxueos** [comment]
我觉得我惹祸了😂

**Comment by haiibo** [comment]
什么惹祸了
