### ISSUE TITLE
请能问能添加一个R2S的 RTL8812BU的USB无线网卡驱动吗?

### ISSUE THREAD

**Issue by 1335344215** [haiibo/OpenWrt#25]
大佬:
请问能添加一个R2S的 RTL8812BU的USB无线网卡驱动吗?
具体芯片见图片
![78eef7a9aacd92a1c36ac1793575469](https://user-images.githubusercontent.com/33363399/190580848-03a66f42-4b64-4a1a-a4f9-e451348bb666.jpg)

**Comment by haiibo** [comment]
L大源码没有 rtl88x2bu 驱动，https://github.com/coolsnowwolf/lede/issues/9340

**Comment by 1335344215** [comment]
好吧,好像是内核版本的问题,5.4.162内核是支持的,后面找遍了全网都没找到支持最新内核又支持这款网卡的![image](https://user-images.githubusercontent.com/33363399/190595680-0066c937-e5df-4a52-9520-00dcc580f666.png)

**Comment by haiibo** [comment]
你可以尝试拉取 immortalwrt  [openwrt-18.06-k5.4] (https://github.com/immortalwrt/immortalwrt/tree/openwrt-18.06-k5.4/package/kernel/rtl88x2bu) 或者 [openwrt-18.06](https://github.com/immortalwrt/immortalwrt/tree/openwrt-18.06/package/kernel/rtl88x2bu) 编译5.4最新内核和5.15试试看是否可用
