### ISSUE TITLE
软件源无法正常安装，更换源也不行，需要安装rndis驱动

### ISSUE THREAD

**Issue by dmserver** [haiibo/OpenWrt#27]
大佬可以集成rndis驱动吗
这样可以把旧手机和随身wifi都利用上

**Comment by haiibo** [comment]
你是什么设备

**Comment by dmserver** [comment]
> 你是什​​么设备

随身wifi刷的op(高通410 自动打开的rndis) 红米note5a手机 魅族mx6手机

**Comment by haiibo** [comment]
我是说你的路由设备

**Comment by dmserver** [comment]
> 你是什​​么设备

rndis 驱动都是一样的

> 我是说你的路由设备

斐讯N1

**Comment by haiibo** [comment]
plus 版本集成了 rndis 驱动的

**Comment by dmserver** [comment]
> plus 版本集成了 rndis 驱动的

哦

**Comment by haiibo** [comment]
如果你使用的 mini 版本，你下载在这包解压 https://github.com/haiibo/OpenWrt/releases/download/ROOTFS_PLUS/Packages.tar.gz 里面是有 rndis 驱动，你可以用 opkg 安装

**Comment by dmserver** [comment]
> 如果你使用的 mini 版本，你下载这个包解压 https://github.com/haiibo/OpenWrt/releases/download/ROOTFS_PLUS/Packages.tar.gz 里面是有 rndis 驱动，你可以用 opkg 安装

谢谢大佬
