### ISSUE TITLE
Missing protocol extension for proto "3g"

### ISSUE THREAD

**Issue by karnadii** [haiibo/OpenWrt#29]
Can not add modem with 3g protocol
```Missing protocol extension for proto "3g"
cannot open /usr/lib/lua/luci/model/cbi/admin_network/proto_3g.lua: No such file or directory
```
![Screenshot 2022-10-04 185843](https://user-images.githubusercontent.com/18657277/193813852-efa24f80-a288-4aaa-9dd2-6abee0d51bd4.png)

I am using the latest release

**Comment by haiibo** [comment]
This is caused by not adding luci-proto-3g, I have added it to the firmware

**Comment by karnadii** [comment]
thanks, it is working now.
