### ISSUE TITLE
根目录空间是否太小？

### ISSUE THREAD

**Issue by qiuxiucai** [haiibo/OpenWrt#32]
network文件都没有创建空间就不够了，1g是否太小了？

**Comment by haiibo** [comment]
你是什么设备，我调整一下

**Comment by qiuxiucai** [comment]
esxi虚拟机img转vmdk安装

**Comment by qiuxiucai** [comment]
x86 64

**Comment by qiuxiucai** [comment]
![Snipaste_2022-10-05_19-06-56](https://user-images.githubusercontent.com/69458598/194046669-9ce6626e-9125-4580-bd14-73833e6cddb2.png)
