### ISSUE TITLE
请问我可以手动调整mount分区吗？

### ISSUE THREAD

**Issue by jinghua625** [haiibo/OpenWrt#4]
比如我安装CloudDrive，需要mount --make-shared /mnt/mmcblk0p3，会导致分区混乱吗？

**Comment by haiibo** [comment]
不会导致分区混乱，你可以df -h看一下哪个分区空间最大，建议用空间最大的分区，默认docker分区最大

**Comment by jinghua625** [comment]
谢谢答疑。我用的N1和我家云，EMMC只有8G,我已经把docker的根目录改到外挂盘了，但是系统的根目录还是满了，我看了一下主要是/usr/bin目录，请问有什么办法给根目录扩容吗？mmcblk0p3 和mmcblk0p4目录都是空的，没有利用上。
