### ISSUE TITLE
希望能够加上iStore，这样装一些插件可以方便些，谢谢！！另外……

### ISSUE THREAD

**Issue by oyanli** [haiibo/OpenWrt#41]
机器：R68s，使用的PLUS固件

我的使用环境，走了一圈只有你这里的6.0核心的比较好用，感恩！！现在想自己编译，不过还没摸进门，但是对一些插件有需求，希望能增加iStore，这样安装一些里面的插件比较方便，应该也不会引起添加太多插件编译失败的问题，谢谢！！

另外，PLUS中的5.15内核的固件安装后不能使用，表现为安装完后，插好网线电脑识别不到机器，6.0的能正常识别，如果作者有空还请检查一下，谢谢！！

**Comment by haiibo** [comment]
r3568只有6.0内核可以用，那个5.15是因为一起打包出现的，你可以当他不存在

**Comment by oyanli** [comment]
谢谢，那请问可以增加iStore吗

**Comment by haiibo** [comment]
可以，我现在添加

**Comment by oyanli** [comment]
谢谢，哪明天就可以用上添加了的，感恩

**Comment by oyanli** [comment]
> 已添加请等待明天上午编译完成

谢谢，感恩！！
