### ISSUE TITLE
刷完固件

### ISSUE THREAD

**Issue by Orzyiii** [haiibo/OpenWrt#42]

**Comment by Orzyiii** [comment]
我刷的arm64   plus       默认地址进不去  四个网口都试了

**Comment by haiibo** [comment]
什么设备？3568的r68s？3568芯片的5.15内核不能用，用6.0内核的

**Comment by haiibo** [comment]
你下的哪个文件，文件名看一下

**Comment by Orzyiii** [comment]
openwrt_rk3568_r68s_R22.11.11_k6.0.10-flippy-79+.img.gz

**Comment by haiibo** [comment]
这个正常应该没问题，我好几个设备都能正常进去，你重新刷试试，默认192.168.1.1

**Comment by Orzyiii** [comment]
这个包  复位键 无效

**Comment by haiibo** [comment]
应该是你那边的问题，昨儿还一个好哥们也是r68s，他用plus正常使用的，https://github.com/haiibo/OpenWrt/issues/41
