### ISSUE TITLE
ARMv8-Plus的CONFIG文件没有CONFIG_TARGET_DEVICE的配置，请问ARMv8-Plus是如何指定设备的

### ISSUE THREAD

**Issue by jiawen94** [haiibo/OpenWrt#43]
你好。我看到在ARMv8-Plus中有很多设备支持，但是在[config文件](https://github.com/haiibo/OpenWrt/blob/main/configs/armv8-plus.config)中并没有找到对应的参数配置。请问这些设备的支持是通过哪些参数控制的

**Comment by haiibo** [comment]
设备支持是通过F大打包脚本对底包openwrt-armvirt-64-default-rootfs.tar.gz打包生成的
![image](https://user-images.githubusercontent.com/85640068/204984808-462515c6-c9e0-4748-82ff-5cf56dee815e.png)
