### ISSUE TITLE
H68K使用ARMv8-Plus的5.15内核镜像无法启动，但是使用6.0内核镜像开机正常

### ISSUE THREAD

**Issue by jiawen94** [haiibo/OpenWrt#44]
设备h68k
在固件归档页面，我下载了5.15内核的固件刷入emmc，启动完全无反应。但是用6.0内核刷入，启动一切正常。
先排除上游仓库lede那边的问题，因为我用自编译的lede 5.15内核时能够启动成功的。会不会时5.15编译时的参数有误，导致系统启动失败？
先反馈一下。

**Comment by haiibo** [comment]
F大打包脚本打包3568设备的只有6.0内核能使用，5.15内核是因为其他设备打包5.15和6.0内核统一出现的，3568设备无视5.15内核就好
