### ISSUE TITLE
adbyby第三方规则无法订阅

### ISSUE THREAD

**Issue by StephenSSR** [haiibo/OpenWrt#46]
设备为n1盒子，在我重新刷入最新固件后，发现广告屏蔽大师不能订阅第三方规则，提示已是最新数据，但规则仍是0条，Adblock Plus 规则数据库可以正常更新

**Comment by haiibo** [comment]
我使用没什么问题。你检查检查
![image](https://user-images.githubusercontent.com/85640068/206917608-aed89ffa-e73b-40e3-bf72-594867b9c87d.png)

**Comment by haiibo** [comment]
检查你的第三方订阅是否被墙，如被墙请在科学上网环境下更新

**Comment by StephenSSR** [comment]
应该不是科学的问题，订阅地址均可正常打开，只有在adbyby无法更新

**Comment by haiibo** [comment]
重新刷机或者重新安装adbyby插件试试

**Comment by StephenSSR** [comment]
重装了adbyby插件，可以正常更新了
