### ISSUE TITLE
lean 6.1已添加wcn6855 无线支持

### ISSUE THREAD

**Issue by zhugunzi** [haiibo/OpenWrt#59]
可以把6855的驱动默认添加进去吗
CONFIG_PACKAGE_ath11k-firmware-wcn6855=y
CONFIG_PACKAGE_kmod-ath=y
CONFIG_PACKAGE_kmod-ath11k=y
CONFIG_PACKAGE_kmod-ath11k-pci=y

**Comment by imjunfeng** [comment]
我也想要耶，大佬加下吧
