### ISSUE TITLE
设备内核支持运存扩容吗？

### ISSUE THREAD

**Issue by Tao173** [haiibo/OpenWrt#6]
RT，emmc扩容支持应该没问题，请问要是扩容运存了，内核dtb是不是也要重新编译才行才能支持呢？

**Comment by haiibo** [comment]
运存扩容了就得更换dtb不然还是原来的运存大小

**Comment by Tao173** [comment]
请问有没有相关修改、编译dtb的教程，还望指点一下。 @haiibo

**Comment by haiibo** [comment]
这个你得问问F大，Arm盒子内核都是F大更新，我没弄过这个

**Comment by Tao173** [comment]
get
