### ISSUE TITLE
X86固件用在exsi 7.0上，4网口直通完，只能识别两个网口插入，另外两个网口显示未插入

### ISSUE THREAD

**Issue by zhb7670** [haiibo/OpenWrt#61]
刷入 openwrt-x86-64-generic-squashfs-combined-efi.img.gz   ，exsi 安装为OP主路由   直通四个网口，只有两个网口检测到网线插入，有两个两口就检测为未插入.啥原因造成的，有办法解决吗?换别人的固件同样的方法安装完，4个网口完美使用！

**Comment by zhb7670** [comment]
config interface 'lan'
	option type 'bridge'
	option proto 'static'
	option ipaddr '192.168.1.10'
	option netmask '255.255.255.0'
	option ip6assign '60'
	option delegate '0'
	option ifname ' eth0 eth2 eth3'

config interface 'lan'
	option type 'bridge'
	option proto 'static'
	option ipaddr '192.168.1.10'
	option netmask '255.255.255.0'
	option ip6assign '60'
	option delegate '0'


原来是这两段代码的区别

**Comment by yasuis** [comment]
我在exsi8.0下用ros+op下没问题，op直通2个网口加一个管理口，虚假机添加pci设备（直通网卡）情况下。
