### ISSUE TITLE
我把你所有代码fork过去，直接编译就不行

### ISSUE THREAD

**Issue by rhwsoft** [haiibo/OpenWrt#64]
难道是人品有问题？

**Comment by hoyoho** [comment]
设置一下action里面的上传权限

**Comment by hoyoho** [comment]
> 难道是人品有问题？

设置一下action里面的权限

**Comment by hoyoho** [comment]
> 难道是人品有问题？

setting-》actions-》general-》Workflow permissions  把read write 还有allow 两个权限打开
