### ISSUE TITLE
能添加8822cs的无线网卡驱动吗。

### ISSUE THREAD

**Issue by 1520316653** [haiibo/OpenWrt#71]
我下载的ophub大佬的openwrt的lede的固件，发现8822cs无线网卡能正常驱动，但是没有istore，而且界面不太好看。
发现大佬的那个高大全版本，界面可以，而且还有istore。但是rtl8822cs的无线网卡，不能驱动，。
那个大佬能加入rtl8822cs的无线网卡驱动吗。
跪谢大佬，编译不太会，哈哈哈啊，、
跪谢大佬。

**Comment by 1520316653** [comment]
ophub说这个8825cs的驱动在编译的时候已经打包在内核了

**Comment by tenacity0** [comment]
E900V22D改的8822cs，下载的最新armbian-bullseye和openwrt-lede，为何都不能驱动？
