### ISSUE TITLE
关于x88king盒子  晶晨s922x没有适配dtb文件

### ISSUE THREAD

**Issue by qili01** [haiibo/OpenWrt#79]
试了gtking系列和am6的dtb文件都启动不了

**Comment by haiibo** [comment]
x88king目前不支持，你可以自行提取设备dtb尝试，https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md#12111-%E6%8F%90%E5%8F%96-bootloader-%E5%92%8C-dtb-%E6%96%87%E4%BB%B6

**Comment by qili01** [comment]
> x88king目录之前没有合适的配置，你可以自行提取设备dtb测试，[如何制作u-boot文件](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md#12111-%E6%8F%90%E5%8F%96-bootloader-%E5%92%8C-dtb-%E6%96%87%E4%BB%B6)

不懂
