### ISSUE TITLE
怎么把这么好用的镜像打包成Docker镜像发到DOCKER网上站去？这个镜像太牛了

### ISSUE THREAD

**Issue by lanyucomputer** [haiibo/OpenWrt#8]
怎么把这么好用的镜像打包成Docker镜像发到DOCKER网上站去?然后用DOCKER PULL命令拉取，这样就可以造福更多的人了.这个镜像太牛了，还有其它芯片的可以加进来吗？

**Comment by lanyucomputer** [comment]
docker pull lanyucomputer/zyxq:latest 这个是我自己用的你镜像打包的docker 镜像，就是有点大，可以用试试看

**Comment by star2k** [comment]
> docker pull lanyucomputer/zyxq:latest 这个是我自己用的你镜像打包的docker 镜像，就是有点大，可以用试试看

有docker部署指令么？

**Comment by lanyucomputer** [comment]
> 

有命令的，有一点麻烦，要ubuntu或类似环境，https://www.vediotalk.com/archives/34583

**Comment by lanyucomputer** [comment]
> > docker pull lanyucomputer/zyxq:latest 这个是我自己用的你镜像打包的docker 镜像，就是有点大，可以用试试看
> 
> 有docker部署指令么？


有命令的，有一点麻烦，要ubuntu或类似环境，https://www.vediotalk.com/archives/34583

**Comment by dizicheng** [comment]
img怎么打包成docker啊，教程都是tar.gz的

**Comment by Java2Boy** [comment]
> > > docker pull lanyucomputer/zyxq:latest 这个是我自己用的你镜像打包的docker 镜像，就是有点大，可以用试试看
> > 
> > 
> > 有docker部署指令么？
> 
> 有命令的，有一点麻烦，要ubuntu或类似环境，https://www.vediotalk.com/archives/34583

有点大啊 老铁，有MINI版 Docker镜像么？求更新
