### ISSUE TITLE
R5C的WLAN灯不亮

### ISSUE THREAD

**Issue by cglcwd** [haiibo/OpenWrt#80]
R5C启用无线且配置LED，重启之后还是不会亮

**Comment by haiibo** [comment]
是否能正常使用，能正常用就行，抱歉我没有设备无法测试

**Comment by cglcwd** [comment]
> 是否能正常使用，能正常用就行，抱歉我没有设备无法测试

我装的无线网卡是mt7921，无线功能是正常的，电源灯、WAN灯和LAN灯都是正常工作的，只是单纯的WLAN灯不会亮而已
