### ISSUE TITLE
关闭LAN的桥接接口之后，信息无法正常显示

### ISSUE THREAD

**Issue by Cod1ng** [haiibo/OpenWrt#88]
使用环境：qnap nas TS-464C 虚拟机安装
版本：OpenWrt R23.06.04 by Haiibo / LuCI Master (git-23.141.16773-28dd4b3)
遇到的问题：
在网络-接口-LAN-物理设置，取消掉“桥接接口”的选项之后，网络-接口会一直显示“正在收集数据..."
<img width="661" alt="image" src="https://github.com/haiibo/OpenWrt/assets/11794907/e5a3a002-5348-4874-8302-10270b72cbbb">
<img width="1006" alt="image" src="https://github.com/haiibo/OpenWrt/assets/11794907/f2a363ca-06ec-4b7b-a024-d1d55cda90f0">
只要勾选上，就能正常显示
<img width="597" alt="image" src="https://github.com/haiibo/OpenWrt/assets/11794907/70f5689d-ea1a-489b-8f4a-741d1ada1863">
试过别的好几个openwrt，都没有这个问题，但别的固件除了没这个问题以外，都没有你的好用，求修复，需要什么别的日志也可以告知

**Comment by haiibo** [comment]
重启

**Comment by Cod1ng** [comment]
重启之后的确正常了，感谢
