### ISSUE TITLE
ARMv8_plus盒子的固件发布页里面没有Packages 文件

### ISSUE THREAD

**Issue by ayacnc** [haiibo/OpenWrt#90]
固件集成的所有 ipk 插件全部打包在 Packages 文件中，可以在 Releases 内进行下载

ARMv8_plus盒子的固件发布页里面没有Packages 文件，不知道在哪

**Comment by haiibo** [comment]
https://github.com/haiibo/OpenWrt/releases/tag/ROOTFS_PLUS
